name: Serverless Connect Test

on:
  schedule:
    - cron: "0/5 * * * *"  # every 5 minutes
  workflow_dispatch:

jobs:
  connect-test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup mysql
        uses: shogo82148/actions-setup-mysql@v1

      - name: connect cluster
        run: |
          mysql -u '4TNwCHfJvXJxs4v.root' -h gateway01.eu-central-1.prod.aws.tidbcloud.com -P 4000 -D test --ssl-mode=VERIFY_IDENTITY --ssl-ca=/etc/ssl/certs/ca-certificates.crt -p${{ secrets.CONNECT_TEST_PSWD }}

      - name: connect branch
        run: |
          mysql --connect-timeout 15 -u '4RCpNUuWxmFv2Ju.root' -h gateway01.eu-central-1.prod.aws.tidbcloud.com -P 4000 -D test --ssl-mode=VERIFY_IDENTITY --ssl-ca=/etc/ssl/certs/ca-certificates.crt -p${{ secrets.CONNECT_TEST_BRANCH_PSWD }}
