# this workflow contains fmt,build,ut fot tikv-client
name: verify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - uses: sane-fmt/action@master
      with:
        args: |
          - --details=diff
          - --color=always
          - zapier
