name: Serverless Driver Connect Test

on:
  schedule:
    - cron: "0/10 * * * *"  # every 10 minutes
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  us-east-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: connect cluster us-east-1
        run: |
          cd example_code/serverless-driver
          npm install @tidbcloud/serverless
          export DATABASE_URL=mysql://nADWvyBQFXhgZxw.root:${{ secrets.TIDB_CLOUD_PASSWORD }}@gateway01.us-east-1.prod.aws.tidbcloud.com/test
          node ConnectTest.js

#  us-west-2:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 16
#
#      - name: connect cluster us-west-2
#        run: |
#          cd example_code/serverless-driver
#          npm install undici @tidbcloud/serverless
#          export DATABASE_URL= mysql://j24i5KNxRJpvEj7.root:${{ secrets.TIDB_CLOUD_PASSWORD }}@gateway01.us-west-2.prod.aws.tidbcloud.com/test
#          node ConnectTest.js
#
#  ap-southeast-1:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 16
#
#      - name: connect cluster ap-northeast-1
#        run: |
#          cd example_code/serverless-driver
#          npm install undici @tidbcloud/serverless
#          export DATABASE_URL= mysql://Nv7fzTqtB8V698S.root:${{ secrets.TIDB_CLOUD_PASSWORD }}@gateway01.ap-northeast-1.prod.aws.tidbcloud.com/test
#          node ConnectTest.js
#
#  ap-northeast-1:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 16
#
#      - name: connect cluster ap-southeast-1
#        run: |
#          cd example_code/serverless-driver
#          npm install undici @tidbcloud/serverless
#          export DATABASE_URL= mysql://eQsaVQSBNukNp7k.root:${{ secrets.TIDB_CLOUD_PASSWORD }}@gateway01.ap-southeast-1.prod.aws.tidbcloud.com/test
#          node ConnectTest.js
#
#  eu-central-1:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 16
#
#      - name: connect cluster eu-central-1
#        run: |
#          cd example_code/serverless-driver
#          npm install undici @tidbcloud/serverless
#          export DATABASE_URL= mysql://Bxoh2PviimqNru3.root:${{ secrets.TIDB_CLOUD_PASSWORD }}@gateway01.eu-central-1.prod.aws.tidbcloud.com/test
#          node ConnectTest.js