name: Serverless Driver Connect Test

on:
  schedule:
    - cron: "0/10 * * * *"  # every 10 minutes
  workflow_dispatch:

jobs:
  us-east-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: connect cluster us-east-1
        run: |
          cd example_code/serverless-driver
          npm install @tidbcloud/serverless
          echo "nADWvyBQFXhgZxw.root:pswd@gateway01.us-east-1.prod.aws.tidbcloud.com"
          export DATABASE_URL=mysql://nADWvyBQFXhgZxw.root:${{ secrets.CLUSTER_PSWD_US_EAST_1 }}@gateway01.us-east-1.prod.aws.tidbcloud.com/test
          node ConnectTest.js

  us-west-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: connect cluster us-west-2
        run: |
          cd example_code/serverless-driver
          npm install @tidbcloud/serverless
          echo "j24i5KNxRJpvEj7.root:pswd@gateway01.us-west-2.prod.aws.tidbcloud.com"
          export DATABASE_URL=mysql://j24i5KNxRJpvEj7.root:${{ secrets.CLUSTER_PSWD_US_WEST_2 }}@gateway01.us-west-2.prod.aws.tidbcloud.com/test
          node ConnectTest.js

  ap-northeast-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: connect cluster ap-northeast-1
        run: |
          cd example_code/serverless-driver
          npm install @tidbcloud/serverless
          echo "Nv7fzTqtB8V698S.root:pswd@gateway01.ap-northeast-1.prod.aws.tidbcloud.com"
          export DATABASE_URL=mysql://Nv7fzTqtB8V698S.root:${{ secrets.CLUSTER_PSWD_AP_NORTHEAST_1 }}@gateway01.ap-northeast-1.prod.aws.tidbcloud.com/test
          node ConnectTest.js

  ap-southeast-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: connect cluster ap-southeast-1
        run: |
          cd example_code/serverless-driver
          npm install @tidbcloud/serverless
          echo "eQsaVQSBNukNp7k.root:pswd@gateway01.ap-southeast-1.prod.aws.tidbcloud.com"
          export DATABASE_URL=mysql://eQsaVQSBNukNp7k.root:${{ secrets.CLUSTER_PSWD_AP_SOUTHEAST_1 }}@gateway01.ap-southeast-1.prod.aws.tidbcloud.com/test
          node ConnectTest.js

  eu-central-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: connect cluster eu-central-1
        run: |
          cd example_code/serverless-driver
          npm install @tidbcloud/serverless
          echo "Bxoh2PviimqNru3.root:pswd@gateway01.eu-central-1.prod.aws.tidbcloud.com"          
          export DATABASE_URL=mysql://Bxoh2PviimqNru3.root:${{ secrets.CLUSTER_PSWD_EU_CENTRAL_1 }}@gateway01.eu-central-1.prod.aws.tidbcloud.com/test
          node ConnectTest.js
